kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: Install node_modules
  commands:
    - npm ci
  - name: Build
  commands:
    - npm run build
  - name: Start
  commands:
    - npm run start
