kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: Install, build and start
  image: node:15.12.0-alpine
  commands:
    - npm ci
    - npm run build
    - npm run start
