kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: Install node_modules
  commands:
  - npm i
- name: Build
  commands:
  - npm run build
- name: Start
  commands:
  - npm run start
