kind: pipeline
type: docker
name: default

steps:

- name: install
  image: node
  commands:
    - npm ci
- name: build
  image: node
  commands:
    - npm run build
- name: start
  image: node
  commands:
    - npm run start
- name: publish
  image: node
  commands:
    - npm run start