kind: pipeline
type: exec
name: default

steps:

- name: Install node_modules
  commands:
    - "npm ci"
- name: Build
  commands:
    - "npm run build"
- name: Start
  commands:
    - "npm run start"
